name: Deploy Lambda (Python)

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  LAMBDA_FUNCTION_NAME: my-lambda-function-github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python (optional, for parity with Lambda runtime)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Match your Lambda runtime

      # Step 3: Package the Lambda function (zip contents of the /lambda folder)
      - name: Package Lambda function
        run: |
          cd lambda
          zip -r ../lambda.zip . -x "*.pyc" "__pycache__/*"

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Deploy the zip to Lambda
      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip \
            --region ${{ secrets.AWS_REGION }}
